# -*- coding: utf-8 -*- 
'''
No.389
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
'''
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        构建字典，对于s中的每一个字母，记录出现的次数，然后对于t中的字母，对应出现的次数减1，如果出现了s中没有的字母，即
        not in dict，则一定是多出来的元素，否则最后dict只剩一个1次的元素即为答案
        """
        dict = {}
        for i in range(len(s)):
            dict[s[i]] = dict.get(s[i],0) + 1
        for j in range(len(t)):
            if t[j] not in dict:
                return t[j]
            dict[t[j]] = dict.get(t[j],0) - 1
            if dict[t[j]] == 0:
                dict.pop(t[j])
        return dict.keys()[0]
        
